In [10]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

# not scientific numbers
pd.set_option('display.float_format', '{:.5f}'.format)
np.set_printoptions(suppress=True)

In [11]:
villagers_df = pd.read_csv("./data/villagers.csv")
villagers_df.columns

Index(['Name', 'Species', 'Gender', 'Personality', 'Hobby', 'Birthday',
       'Catchphrase', 'Favorite Song', 'Style 1', 'Style 2', 'Color 1',
       'Color 2', 'Wallpaper', 'Flooring', 'Furniture List', 'Filename',
       'Unique Entry ID'],
      dtype='object')

In [12]:
villagers_df["Species"].value_counts()

Species
Cat          23
Rabbit       20
Squirrel     18
Frog         18
Duck         17
Dog          16
Cub          16
Bear         15
Pig          15
Horse        15
Mouse        15
Bird         13
Penguin      13
Sheep        13
Wolf         11
Elephant     11
Deer         10
Ostrich      10
Gorilla       9
Chicken       9
Eagle         9
Koala         9
Goat          8
Kangaroo      8
Monkey        8
Hamster       8
Alligator     7
Lion          7
Anteater      7
Hippo         7
Tiger         7
Bull          6
Rhino         6
Cow           4
Octopus       3
Name: count, dtype: int64

In [13]:
villagers_df["Personality"].value_counts()

Personality
Lazy          60
Normal        59
Snooty        55
Cranky        55
Jock          55
Peppy         49
Smug          34
Big Sister    24
Name: count, dtype: int64

In [14]:
species_count_df = pd.DataFrame(villagers_df['Personality'].value_counts()).reset_index()
species_count_df.columns = ['Personality', 'Amount']
species_count_df

  Personality  Amount
0        Lazy      60
1      Normal      59
2      Snooty      55
3      Cranky      55
4        Jock      55
5       Peppy      49
6        Smug      34
7  Big Sister      24

# extra data

In [15]:
reactions_df = pd.read_csv("./data/reactions.csv")
reactions_df

,Name,Source,Source Notes,Internal ID,Unique Entry ID
0,Aggravation,Peppy,NaN,NaN,6suhKYAAhh5QMKt64
1,Agreement,Cranky,NaN,NaN,7smqwK9J7eFBxta28
2,Amazed,Snooty,NaN,NaN,vosig4bbr4kPq57AT
3,Apologetic,Big Sister,NaN,NaN,jBKsQYCAd7PtymQeB
4,Bashfulness,Lazy,NaN,NaN,wzvKbFrEJCseTohoz
5,Bewilderment,Cranky,NaN,NaN,WRSSRZMtM6rXfXBrR
6,Cold Chill,Big Sister,NaN,NaN,K62u2owKFDLmPCB3Q
7,Confident,Big Sister,Requires a high level of friendship,NaN,TGifHTbyLBh4f3gDQ
8,Curiosity,Peppy,NaN,NaN,SskgipgnKzm5TsK7d
9,Daydreaming,Normal,Requires a high level of friendship,NaN,JFrTBJCEaX5R4kABT
10,Delight,All,NaN,NaN,F9DpGeqZzDeSTh2bq
11,Disagreement,Big Sister,NaN,NaN,Bw5YBM6iuWgMzutWq
12,Distress,Jock,NaN,NaN,vsSjQBZXPeSK6uDTK
13,Dozing,Smug,NaN,NaN,2vvgAacGjthcFW5Qa
14,Encouraging,Jock,NaN,NaN,fomfML4NWdY8x6adv
15,Fearful,Normal,NaN,NaN,noKrWYCMSWcH4jwvi
16,Flourish,Jock,Requires a high level of friendship,NaN,5QDD3DcwdPhbGoJAf
17,Glee,Normal,NaN,NaN,8nAwdhzZfotqpLC9R
18,Greetings,All,NaN,NaN,oE6uqhZYjYfuqb55n
19,Happiness,Peppy,NaN,NaN,TWENXBbBENgnFiGq3
20,Heartbreak,Smug,NaN,NaN,ex6gKZu6zsyd6MgDr
21,Inspiration,Cranky,Requires a high level of friendship,NaN,8ux4ddfibJQR2EuWW
22,Intense,Snooty,NaN,NaN,X2kzqTaPwtG6SGNT8
23,Joy,All,NaN,NaN,fSNyHJHgLKac5mSLT
24,Laughter,Big Sister,NaN,NaN,EBenMHMpwnkMgS6eg
25,Love,Snooty,Requires a high level of friendship,NaN,GvAsErCFuGAcMAeXM
26,Mischief,Peppy,Requires a high level of friendship,NaN,E7it7yLfFaddFvEhQ
27,Mistaken,Lazy,NaN,NaN,DPR7WWkmR36Bsf2LG
28,Pleased,Normal,NaN,NaN,Z3MuKfQMaH3D8vkPA
29,Pride,Lazy,Requires a high level of friendship,NaN,xKoQpdJMtocNFRckm
30,Resignation,Smug,NaN,NaN,7YdF3ZMr95XP3FaoW
31,Sadness,Normal,NaN,NaN,Wo8q6KhPtL2CYwat4
32,Sheepishness,Cranky,NaN,NaN,NaN
33,Shocked,Jock,NaN,NaN,bn29da8SNdMYYyWAa
34,Showmanship,Smug,Requires a high level of friendship,NaN,Bj5iG7kc6tLND9bjn
35,Shyness,Lazy,NaN,NaN,9H7jt7AGKbh6mW4y8
36,Sighing,Snooty,NaN,NaN,ntjLqg82EQNsgnzYA
37,Sleepy,Peppy,NaN,NaN,9e5BhxmqtMurNWqW4
38,Smirking,Smug,NaN,NaN,KDAWT9zDKpufEWgaW
39,Sneezing,Jock,NaN,NaN,F6Dkk4PGtjDMCgry3
40,Sorrow,Lazy,NaN,NaN,W8nngMS98uwpHHW4m
41,Surprise,All,NaN,NaN,7jmkZiSxrYT7MMm4P
42,Thought,Snooty,NaN,NaN,HEFCeCGtJ7Bkb5PXG
43,Worry,Cranky,NaN,NaN,TygKeKxvotLEzWqvY

In [16]:
#Drop the columns we dont want
new_reactions_df = reactions_df.dropna(axis=1, how='all')

#cleadned df
print(new_reactions_df.head())

          Name      Source Source Notes    Unique Entry ID
0  Aggravation       Peppy          NaN  6suhKYAAhh5QMKt64
1    Agreement      Cranky          NaN  7smqwK9J7eFBxta28
2       Amazed      Snooty          NaN  vosig4bbr4kPq57AT
3   Apologetic  Big Sister          NaN  jBKsQYCAd7PtymQeB
4  Bashfulness        Lazy          NaN  wzvKbFrEJCseTohoz

In [17]:
new_reactions_df['Source'].unique()

array(['Peppy', 'Cranky', 'Snooty', 'Big Sister', 'Lazy', 'Normal', 'All',
       'Jock', 'Smug'], dtype=object)

## match with 'source' with 'personality' from villagers df

In [18]:
new_reactions_df = new_reactions_df.rename(columns= {'Source':'Personality'})
new_reactions_df['Personality'] = new_reactions_df['Personality'].str.strip()
new_reactions_df['Personality'].unique()

array(['Peppy', 'Cranky', 'Snooty', 'Big Sister', 'Lazy', 'Normal', 'All',
       'Jock', 'Smug'], dtype=object)

# merge df's by column with same name

In [19]:
# Merging datasets to combine relevant information
merged_df = pd.merge(species_count_df, new_reactions_df)
merged_df = merged_df.rename(columns={"Name" : "Reaction"})

merged_df

,Personality,Amount,Reaction,Source Notes,Unique Entry ID
0,Lazy,60,Bashfulness,NaN,wzvKbFrEJCseTohoz
1,Lazy,60,Mistaken,NaN,DPR7WWkmR36Bsf2LG
2,Lazy,60,Pride,Requires a high level of friendship,xKoQpdJMtocNFRckm
3,Lazy,60,Shyness,NaN,9H7jt7AGKbh6mW4y8
4,Lazy,60,Sorrow,NaN,W8nngMS98uwpHHW4m
5,Normal,59,Daydreaming,Requires a high level of friendship,JFrTBJCEaX5R4kABT
6,Normal,59,Fearful,NaN,noKrWYCMSWcH4jwvi
7,Normal,59,Glee,NaN,8nAwdhzZfotqpLC9R
8,Normal,59,Pleased,NaN,Z3MuKfQMaH3D8vkPA
9,Normal,59,Sadness,NaN,Wo8q6KhPtL2CYwat4
10,Snooty,55,Amazed,NaN,vosig4bbr4kPq57AT
11,Snooty,55,Intense,NaN,X2kzqTaPwtG6SGNT8
12,Snooty,55,Love,Requires a high level of friendship,GvAsErCFuGAcMAeXM
13,Snooty,55,Sighing,NaN,ntjLqg82EQNsgnzYA
14,Snooty,55,Thought,NaN,HEFCeCGtJ7Bkb5PXG
15,Cranky,55,Agreement,NaN,7smqwK9J7eFBxta28
16,Cranky,55,Bewilderment,NaN,WRSSRZMtM6rXfXBrR
17,Cranky,55,Inspiration,Requires a high level of friendship,8ux4ddfibJQR2EuWW
18,Cranky,55,Sheepishness,NaN,NaN
19,Cranky,55,Worry,NaN,TygKeKxvotLEzWqvY
20,Jock,55,Distress,NaN,vsSjQBZXPeSK6uDTK
21,Jock,55,Encouraging,NaN,fomfML4NWdY8x6adv
22,Jock,55,Flourish,Requires a high level of friendship,5QDD3DcwdPhbGoJAf
23,Jock,55,Shocked,NaN,bn29da8SNdMYYyWAa
24,Jock,55,Sneezing,NaN,F6Dkk4PGtjDMCgry3
25,Peppy,49,Aggravation,NaN,6suhKYAAhh5QMKt64
26,Peppy,49,Curiosity,NaN,SskgipgnKzm5TsK7d
27,Peppy,49,Happiness,NaN,TWENXBbBENgnFiGq3
28,Peppy,49,Mischief,Requires a high level of friendship,E7it7yLfFaddFvEhQ
29,Peppy,49,Sleepy,NaN,9e5BhxmqtMurNWqW4
30,Smug,34,Dozing,NaN,2vvgAacGjthcFW5Qa
31,Smug,34,Heartbreak,NaN,ex6gKZu6zsyd6MgDr
32,Smug,34,Resignation,NaN,7YdF3ZMr95XP3FaoW
33,Smug,34,Showmanship,Requires a high level of friendship,Bj5iG7kc6tLND9bjn
34,Smug,34,Smirking,NaN,KDAWT9zDKpufEWgaW
35,Big Sister,24,Apologetic,NaN,jBKsQYCAd7PtymQeB
36,Big Sister,24,Cold Chill,NaN,K62u2owKFDLmPCB3Q
37,Big Sister,24,Confident,Requires a high level of friendship,TGifHTbyLBh4f3gDQ
38,Big Sister,24,Disagreement,NaN,Bw5YBM6iuWgMzutWq
39,Big Sister,24,Laughter,NaN,EBenMHMpwnkMgS6eg